project:
  title: "勉強ノート"
  type: website
  render:
    - "*.qmd"

metadata-files:
  - api/_sidebar.yml

publish:
  provider: gh-pages

website:
  title: "勉強ノート"
  page-navigation: true
  navbar:
    left:
      - file: index.qmd
        text: Top Page
      # - href: api/
      #   text: Reference
    tools:
    - icon: github
      menu:
        - text: Source Code
          href: https://github.com/wakabame/study_note
  sidebar:
    - id: get-started
      title: Get Started
      style: floating
      align: left
      contents:
        - index.qmd
        - section: "非線形最適制御入門"
          href: "nonlinear_contol/index.html"
          contents:
            - "nonlinear_contol/discrete.qmd"
            - "nonlinear_contol/discrete_and_continuous.qmd"
        # - section: "Function Reference"
        #   contents: "api/*"
        # - section: "Notebooks"
        #   contents: "notebook/*"

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    html-math-method: katex
    classoption: fleqn
    grid:
      body-width: 1200px

quartodoc:
  style: pkgdown
  parser: numpy
  package: study_note
  dir: api
  sidebar: "api/_sidebar.yml"

  sections:
    - title: sample
      desc: ""
      contents:
        - sample.sample_add_int
